### ISSUE TITLE
リライトプラグインの要求仕様をまとめる

### ISSUE THREAD

**Issue by fumikito** [kuno1/rewrite-now#1]
- なにをすべきか
- 箇条書きで

**Comment by kzoou** [comment]
- リライトすべきと判断した記事にフラグを立てられる（一旦、手動）
- 最終更新日を投稿一覧画面に表示
- 最終更新日から一定期間更新していなければプッシュ
  - 一括で期間設定
  - 記事ごとに個別設定で一括の設定を上書き可能
- リライト対象記事（すでに公開済み記事）の下書き保存

**Comment by fumikito** [comment]
#2 #3 #4 #5 にまとめたので終了。
